sudo ./check_packages.sh
sleep 3
sudo ./version-check.sh
sleep 3
sudo ./disk_setup.sh
sleep 3
sudo ./get_packages.sh
sleep 3
sudo ./get_patches.sh
sleep 3
sudo ./groundwork.sh
sleep 3
sudo ./toolchain.sh
sleep 3
sudo ./toolchain2.sh
sleep 3
sudo ./toolchain3.sh
sleep 3
sudo ./toolchain4.sh
sleep 3
sudo ./toolchain5.sh
sleep 3
sudo ./toolchain6.sh
